import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  TouchableOpacity,
  SafeAreaView,
  ActivityIndicator
} from 'react-native';

import { api } from '@pixelence/convex';

export default function ReportDetailScreen({ route, navigation }) {
  const { reportId } = route.params;
  const [report, setReport] = useState(undefined);

  useEffect(() => {
    api.reports.getReportById({ reportId })
      .then(data => setReport(data))
      .catch(() => setReport(null));
  }, [reportId]);

  if (report === undefined) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#3B82F6" />
      </View>
    );
  }

  if (report === null) {
      return (
          <View style={styles.center}>
              <Text>Report not found</Text>
          </View>
      );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Text style={styles.backButtonText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Report Results</Text>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent}>
        {/* Patient Summary Card */}
        <View style={styles.patientCard}>
          <Text style={styles.patientName}>Patient ID: {report.patientId}</Text>
          <View style={styles.metaRow}>
            <Text style={styles.metaText}>Status ID: {report.status}</Text>
            <View style={styles.statusBadge}>
              <Text style={styles.statusText}>{report.status.toUpperCase()}</Text>
            </View>
          </View>
        </View>

        {/* Study Details */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Study Information</Text>
          <View style={styles.infoBox}>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Job ID</Text>
              <Text style={styles.infoValue}>{report.jobId}</Text>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Report Date</Text>
              <Text style={styles.infoValue}>{new Date(report.createdAt).toLocaleDateString()}</Text>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Radiologist</Text>
              <Text style={styles.infoValue}>{report.radiologistId}</Text>
            </View>
          </View>
        </View>

        {/* Findings */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Clinical Findings</Text>
          <View style={styles.contentBox}>
            <Text style={styles.contentText}>{report.findings}</Text>
          </View>
        </View>

        {/* Impression */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Impression</Text>
          <View style={[styles.contentBox, styles.highlightBox]}>
            <Text style={styles.contentText}>{report.impression}</Text>
          </View>
        </View>

        {/* Medical Imaging Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Medical Imaging</Text>
          <View style={styles.imagingBox}>
            <View style={styles.imageThumbnails}>
              {['T1', 'T2', 'FLAIR'].map((type, idx) => (
                <View key={idx} style={styles.imagePreview}>
                   <Text style={styles.previewText}>{type}</Text>
                </View>
              ))}
            </View>
            <TouchableOpacity 
              style={styles.viewImagesButton}
              onPress={() => navigation.navigate('DicomViewer', { jobId: report.jobId })}
            >
              <Text style={styles.viewImagesText}>Open Full DICOM Viewer</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Footer Actions */}
        <TouchableOpacity style={styles.printButton}>
          <Text style={styles.printButtonText}>Download PDF Report</Text>
        </TouchableOpacity>
        
        <Text style={styles.disclaimer}>
          Digital report generated by Pixelence MRI System. This report should be reviewed with your primary physician.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    padding: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    marginRight: 15,
  },
  backButtonText: {
    color: '#3B82F6',
    fontWeight: '600',
    fontSize: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E293B',
  },
  scrollContent: {
    padding: 20,
  },
  patientCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 25,
    marginBottom: 25,
  },
  patientName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 8,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaText: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '500',
  },
  statusBadge: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  infoBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  infoLabel: {
    color: '#94A3B8',
    fontSize: 14,
  },
  infoValue: {
    color: '#1E293B',
    fontWeight: '600',
    fontSize: 14,
  },
  contentBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  highlightBox: {
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
  },
  contentText: {
    fontSize: 15,
    color: '#334155',
    lineHeight: 24,
  },
  imagingBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  imageThumbnails: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  imagePreview: {
    flex: 1,
    aspectRatio: 1,
    backgroundColor: '#1E293B',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
  },
  viewImagesButton: {
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  viewImagesText: {
    color: '#3B82F6',
    fontWeight: '700',
    fontSize: 14,
  },
  printButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  printButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  disclaimer: {
    fontSize: 12,
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 10,
  }
});
